/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Aldo_Consultas;
import Clases.Aldo_Controlador;
import Clases.Aldo_EventosKey;
import Clases.Aldo_General;
import Clases.Aldo_Impresora;
import Clases.Aldo_Mensajes;
import Clases.Aldo_Tabla;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import java.awt.Image;

/**
 *
 * @author Aldo Omar
 */
public class JInt_ValidarArchivos extends javax.swing.JInternalFrame {

    Aldo_Controlador controlador = new Aldo_Controlador();
    Aldo_Tabla tabla = new Aldo_Tabla();
    Aldo_Mensajes mensaje = new Aldo_Mensajes();
    Aldo_Consultas consulta = new Aldo_Consultas();
    Aldo_EventosKey evento = new Aldo_EventosKey();
    Aldo_Impresora impresora = new Aldo_Impresora();
    Aldo_General general = new Aldo_General();
    private DefaultTableModel modelo;
    private DefaultTableModel modeloA;
    private String numacta = "";
    public static String rutaArch = "";
    public static String nombreArch = "";
    private String directorioPrincipal = "";
    private String nombreArchivo = "";
    private String idarc = "";

    /**
     * Creates new form JInt_ListadoArchivos
     */
    public JInt_ValidarArchivos() {
        initComponents();
        general.setIconoJInternal(this, "/Imagenes/logo.png");
        tituloTabla();
        cargarTabla();
        tituloTablaArc();
        tabla.tablaNoEditable(jTableListadoRegistros);
        tabla.tablaNoEditable(jTableListadoArchivos);
        consulta.llenarCombo("select * from tipo_reg", jComboBoxBuscar, 2);
    }

    public void tituloTabla() {
        String[] titulo = {"ID", "DNI", "APELLIDOS Y NOMBRES", "GENERO", "DIRECCIÓN", "FEC. NAC.", "TIPO REGISTRO",
            "N° ACTA", "DISTRITO", "PROVINCIA", "DEPARTAMENTO", "FEC. REG.", "HRA. REG."};
        modelo = new DefaultTableModel(null, titulo);
        modelo.setColumnIdentifiers(titulo);
        jTableListadoRegistros.setModel(modelo);
    }

    public void cargarTabla() {
        tabla.MostrarEnTabla("CALL listRegistrosVal()", jTableListadoRegistros, modelo, 13);
        tabla.ocultarColumnasTabla(jTableListadoRegistros, 0);
        tabla.setMaxWidthColumnTable(jTableListadoRegistros, 70, 1);
        tabla.setMaxWidthColumnTable(jTableListadoRegistros, 250, 2);
    }

    public void buscarArchivo() {
        controlador.BuscarDato("CALL searchRegistrosVal(?)", modelo, 13, jCTextFieldBuscar);
    }

    public void cargarTablaFiltro(String dato) {
        tabla.MostrarEnTabla("CALL listRegistrosValFiltrar('" + dato + "')", jTableListadoRegistros, modelo, 13);
        tabla.ocultarColumnasTabla(jTableListadoRegistros, 0);
        tabla.setMaxWidthColumnTable(jTableListadoRegistros, 70, 1);
        tabla.setMaxWidthColumnTable(jTableListadoRegistros, 250, 2);
    }

    public void tituloTablaArc() {
        String[] titulo = {"ID", "DOCUMENTO", "N° LIBRO", "ARCHIVO", "FEC. SUBIDO", "HRA. SUBIDO", "RUTA ARCHIVO", "ESTADO"};
        modeloA = new DefaultTableModel(null, titulo);
        modeloA.setColumnIdentifiers(titulo);
        jTableListadoArchivos.setModel(modeloA);
        //Ocultamos las columnas
        tabla.ocultarColumnasTabla(jTableListadoArchivos, 0);
        tabla.ocultarColumnasTabla(jTableListadoArchivos, 6);
        tabla.setMaxWidthColumnTable(jTableListadoArchivos, 400, 3);
    }

    public void cargarTablaArc(String numac) {
        tabla.MostrarEnTabla("CALL listArchivosVal('" + numac + "')", jTableListadoArchivos, modeloA, 8);
        //Ocultamos las columnas
        tabla.ocultarColumnasTabla(jTableListadoArchivos, 0);
        tabla.ocultarColumnasTabla(jTableListadoArchivos, 6);
        tabla.setMaxWidthColumnTable(jTableListadoArchivos, 400, 3);
    }

    public void validarArchivo() {
        try {
            String sql = "CALL editValidarArchivo("
                    + "'" + idarc + "'"
                    + " );";
            mensaje.mensajeInformacion(consulta.CrearRegistro(sql));
        } catch (Exception e) {
            mensaje.mensajeError("Validar el archivo");
        }
    }
    public void desvalidarArchivo() {
        try {
            String sql = "CALL editDesvalidarArchivo("
                    + "'" + idarc + "'"
                    + " );";
            mensaje.mensajeInformacion(consulta.CrearRegistro(sql));
        } catch (Exception e) {
            mensaje.mensajeError("Desvalidar el archivo");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListadoRegistros = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jCTextFieldBuscar = new ControlSwing.JCTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxBuscar = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jCButtonValidar = new ControlSwing.JCButton();
        jCButtonSalir = new ControlSwing.JCButton();
        jCButtonAbrir = new ControlSwing.JCButton();
        jCButtonDesvalidar = new ControlSwing.JCButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListadoArchivos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelApellidosNombres = new javax.swing.JLabel();
        jLabelTipoRegistro = new javax.swing.JLabel();
        jLabelNumActa = new javax.swing.JLabel();

        setTitle("VALIDAR ARCHIVOS");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3), "LISTADO DE TODOS LOS REGISTROS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 255))); // NOI18N

        jTableListadoRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableListadoRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListadoRegistrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListadoRegistros);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Buscar");

        jCTextFieldBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCTextFieldBuscar.setPlaceholder("Ingrese un dato para buscar");
        jCTextFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextFieldBuscarActionPerformed(evt);
            }
        });
        jCTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCTextFieldBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCTextFieldBuscarKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Filtrar");

        jComboBoxBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccionar --" }));
        jComboBoxBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1256, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCTextFieldBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jCTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(jComboBoxBuscar, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3), "CONTROLES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 255))); // NOI18N

        jCButtonValidar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/check.png"))); // NOI18N
        jCButtonValidar.setText("Validar");
        jCButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCButtonValidarActionPerformed(evt);
            }
        });

        jCButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salir.png"))); // NOI18N
        jCButtonSalir.setText("Salir");
        jCButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCButtonSalirActionPerformed(evt);
            }
        });

        jCButtonAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/abrir.png"))); // NOI18N
        jCButtonAbrir.setText("Abrir");
        jCButtonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCButtonAbrirActionPerformed(evt);
            }
        });

        jCButtonDesvalidar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/desvalidar.png"))); // NOI18N
        jCButtonDesvalidar.setText("Desvalidar");
        jCButtonDesvalidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCButtonDesvalidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jCButtonAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCButtonValidar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCButtonDesvalidar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCButtonValidar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCButtonDesvalidar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCButtonAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3), "LISTADO DE ARCHIVOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 255))); // NOI18N

        jTableListadoArchivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableListadoArchivos);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Apellidos y Nombres:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("N° de Acta:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Tipo Registro:");

        jLabelApellidosNombres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelApellidosNombres.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelTipoRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTipoRegistro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelNumActa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumActa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelApellidosNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTipoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNumActa, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabelApellidosNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTipoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumActa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextFieldBuscarActionPerformed

    private void jCTextFieldBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCTextFieldBuscarKeyReleased
        // TODO add your handling code here:
        evento.mayusculas(evt, jCTextFieldBuscar);
        buscarArchivo();
    }//GEN-LAST:event_jCTextFieldBuscarKeyReleased

    private void jCTextFieldBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCTextFieldBuscarKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_jCTextFieldBuscarKeyTyped

    private void jCButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCButtonValidarActionPerformed
        // TODO add your handling code here:
        if (jTableListadoArchivos.getSelectedRow() >= 0) {
            String estadoAr = modeloA.getValueAt(jTableListadoArchivos.getSelectedRow(), 7).toString();
            idarc = modeloA.getValueAt(jTableListadoArchivos.getSelectedRow(), 0).toString();
            if (estadoAr.equals("0")) {
                validarArchivo();
                cargarTabla();
                cargarTablaArc(numacta);
            } else {
                mensaje.mensajeInformacion("El archivo seleccionado ya está validado.");
            }
        } else {
            mensaje.mensajeInformacion("Debe seleccionar un archivo para validar.");
        }
    }//GEN-LAST:event_jCButtonValidarActionPerformed

    private void jCButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCButtonSalirActionPerformed
        // TODO add your handling code here:
        mensaje.cerrarVentanaSinConfirmarJI(this);
    }//GEN-LAST:event_jCButtonSalirActionPerformed

    private void jTableListadoRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListadoRegistrosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            if (jTableListadoRegistros.getSelectedRowCount() == 1) {
                numacta = modelo.getValueAt(jTableListadoRegistros.getSelectedRow(), 7).toString();
                jLabelApellidosNombres.setText(modelo.getValueAt(jTableListadoRegistros.getSelectedRow(), 2).toString());
                jLabelTipoRegistro.setText(modelo.getValueAt(jTableListadoRegistros.getSelectedRow(), 6).toString());
                jLabelNumActa.setText(modelo.getValueAt(jTableListadoRegistros.getSelectedRow(), 7).toString());
                cargarTablaArc(numacta);
            }
        }
    }//GEN-LAST:event_jTableListadoRegistrosMouseClicked

    private void jComboBoxBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBuscarActionPerformed
        // TODO add your handling code here:
        if (jComboBoxBuscar.getSelectedIndex() != 0) {
            cargarTablaFiltro(jComboBoxBuscar.getSelectedItem().toString());
        } else {
            cargarTabla();
        }
    }//GEN-LAST:event_jComboBoxBuscarActionPerformed

    private void jCButtonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCButtonAbrirActionPerformed
        // TODO add your handling code here:
        if (jTableListadoArchivos.getSelectedRow() >= 0) {
            nombreArchivo = modeloA.getValueAt(jTableListadoArchivos.getSelectedRow(), 6).toString();
            directorioPrincipal = consulta.devolverRegistroDato("select * from directorio", 2);
            rutaArch = directorioPrincipal + nombreArchivo;
            nombreArch = modeloA.getValueAt(jTableListadoArchivos.getSelectedRow(), 3).toString();
            String ultimoscarac3 = rutaArch.substring(rutaArch.length() - 3, rutaArch.length());
            if (ultimoscarac3.equals("pdf")) {
                impresora.abrirDoc(rutaArch);
                //                mensaje.mensajeInformacion("El expediente " + nombreArch + " se esta abriendo.");
            } else {
                impresora.abrirDoc(rutaArch);
                //                mensaje.mensajeInformacion("La constancia " + nombreArch + " se esta abriendo.");
            }
        } else {
            mensaje.mensajeInformacion("Debe seleccionar un archivo para abrir.");
        }
    }//GEN-LAST:event_jCButtonAbrirActionPerformed

    private void jCButtonDesvalidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCButtonDesvalidarActionPerformed
        // TODO add your handling code here:
        if (jTableListadoArchivos.getSelectedRow() >= 0) {
            String estadoAr = modeloA.getValueAt(jTableListadoArchivos.getSelectedRow(), 7).toString();
            idarc = modeloA.getValueAt(jTableListadoArchivos.getSelectedRow(), 0).toString();
            if (estadoAr.equals("1")) {
                desvalidarArchivo();
                cargarTabla();
                cargarTablaArc(numacta);
            } else {
                mensaje.mensajeInformacion("El archivo seleccionado no está validado.");
            }
        } else {
            mensaje.mensajeInformacion("Debe seleccionar un archivo para desvalidar.");
        }
    }//GEN-LAST:event_jCButtonDesvalidarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ControlSwing.JCButton jCButtonAbrir;
    private ControlSwing.JCButton jCButtonDesvalidar;
    private ControlSwing.JCButton jCButtonSalir;
    private ControlSwing.JCButton jCButtonValidar;
    private ControlSwing.JCTextField jCTextFieldBuscar;
    private javax.swing.JComboBox<String> jComboBoxBuscar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelApellidosNombres;
    private javax.swing.JLabel jLabelNumActa;
    private javax.swing.JLabel jLabelTipoRegistro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableListadoArchivos;
    private javax.swing.JTable jTableListadoRegistros;
    // End of variables declaration//GEN-END:variables
}
