/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Aldo_Consultas;
import Clases.Aldo_Fechas;
import Clases.Aldo_General;
import Clases.Aldo_Mensajes;

/**
 *
 * @author Aldo Omar
 */
public class JInt_FechaHora extends javax.swing.JInternalFrame {

    Aldo_Mensajes mensaje = new Aldo_Mensajes();
    Aldo_Consultas consulta = new Aldo_Consultas();
    Aldo_General general = new Aldo_General();
    Aldo_Fechas fecha = new Aldo_Fechas();
    public static String fechaImportante = "";
    public static String horaImportante = "";

    /**
     * Creates new form JInt_FechaHora
     */
    public JInt_FechaHora() {
        initComponents();
        general.setIconoJInternal(this, "/Imagenes/logo.png");
    }

    public boolean validarCampos() {
        boolean valor = false;
        if (jDateChooserFecha.getDate() != null) {
            if (timeChooserHora.getText().length() != 0) {
                valor = true;
            } else {
                mensaje.mensajeError("Debe ingresar la " + jLabelHora.getText() + ".");
                timeChooserHora.requestFocus();
            }
        } else {
            mensaje.mensajeError("Debe ingresar la " + jLabelFecha.getText() + ".");
            jDateChooserFecha.requestFocusInWindow();
        }
        return valor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelFecha = new javax.swing.JLabel();
        jDateChooserFecha = new com.toedter.calendar.JDateChooser();
        jLabelHora = new javax.swing.JLabel();
        timeChooserHora = new org.bolivia.time.TimeChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jCButtonAgregarRN = new ControlSwing.JCButton();
        jCButtonCancelarRN = new ControlSwing.JCButton();

        setTitle("IMPORTANTE");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelFecha.setText("Fecha de matrimonio*");

        jDateChooserFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDateChooserFechaKeyPressed(evt);
            }
        });

        jLabelHora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelHora.setText("Hora de matrimonio*");

        timeChooserHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                timeChooserHoraKeyPressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("FECHAS IMPORTANTES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jCButtonAgregarRN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/agregar.png"))); // NOI18N
        jCButtonAgregarRN.setText("Agregar");
        jCButtonAgregarRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCButtonAgregarRNActionPerformed(evt);
            }
        });

        jCButtonCancelarRN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        jCButtonCancelarRN.setText("Cancelar");
        jCButtonCancelarRN.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jCButtonCancelarRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCButtonCancelarRNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelFecha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCButtonAgregarRN, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeChooserHora, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHora)
                            .addComponent(jCButtonCancelarRN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeChooserHora, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCButtonCancelarRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCButtonAgregarRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDateChooserFechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooserFechaKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jDateChooserFechaKeyPressed

    private void timeChooserHoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_timeChooserHoraKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_timeChooserHoraKeyPressed

    private void jCButtonAgregarRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCButtonAgregarRNActionPerformed
        // TODO add your handling code here:
        if (validarCampos()) {
            if (jCButtonAgregarRN.getText().equals("Aceptar")) {
                try {
                    String sql = "CALL updateFecMatrimonio("
                            + "'" + fecha.Formato_AMD(jDateChooserFecha.getDate()) + "',"
                            + "'" + fecha.HoraMysql(timeChooserHora.getText()) + "',"
                            + "'" + JInt_Registro.idregistroFecRM + "'"
                            + " );";
                    mensaje.mensajeInformacion(consulta.CrearRegistro(sql));
                    mensaje.cerrarVentanaSinConfirmarJI(this);
                } catch (Exception e) {
                    mensaje.mensajeError("Error al actualizar la fecha del matrimonio");
                }
            } else if (jCButtonAgregarRN.getText().equals("Modificar")) {
                try {
                    String sql = "CALL updateFecMatrimonio("
                            + "'" + fecha.Formato_AMD(jDateChooserFecha.getDate()) + "',"
                            + "'" + fecha.HoraMysql(timeChooserHora.getText()) + "',"
                            + "'" + JInt_Registro.idregistroFecRD + "'"
                            + " );";
                    mensaje.mensajeInformacion(consulta.CrearRegistro(sql));
                    mensaje.cerrarVentanaSinConfirmarJI(this);
                } catch (Exception e) {
                    mensaje.mensajeError("Error al actualizar la fecha de defunción");
                }
            } else {
                if (jLabelFecha.getText().equals("Fecha de matrimonio*")) {
                    horaImportante = fecha.HoraMysql(timeChooserHora.getText());
                    fechaImportante = fecha.Formato_AMD(jDateChooserFecha.getDate());
                    mensaje.mensajeInformacion("Agregado correctamente");
                    mensaje.cerrarVentanaSinConfirmarJI(this);
                } else {
                    horaImportante = fecha.HoraMysql(timeChooserHora.getText());
                    fechaImportante = fecha.Formato_AMD(jDateChooserFecha.getDate());
                    mensaje.mensajeInformacion("Agregado correctamente");
                    mensaje.cerrarVentanaSinConfirmarJI(this);
                }
            }

        }
    }//GEN-LAST:event_jCButtonAgregarRNActionPerformed

    private void jCButtonCancelarRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCButtonCancelarRNActionPerformed
        // TODO add your handling code here:
        mensaje.cerrarVentanaSinConfirmarJI(this);
    }//GEN-LAST:event_jCButtonCancelarRNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static ControlSwing.JCButton jCButtonAgregarRN;
    private ControlSwing.JCButton jCButtonCancelarRN;
    public static com.toedter.calendar.JDateChooser jDateChooserFecha;
    private javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabelFecha;
    public static javax.swing.JLabel jLabelHora;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static org.bolivia.time.TimeChooser timeChooserHora;
    // End of variables declaration//GEN-END:variables
}
